/**
 * Supervisory Report - OpenAPI 3.0
 * APIs For Supervisory Report
 *
 * OpenAPI spec version: 1.0.11
 * Contact: vivek.singh-v@cms.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Report { 
    FromDate?: string;
    ToDate?: string;
    AtmId?: string;
}